## Jaccard Similarity

In [1]:
import numpy as np

In [2]:
# Jaccard Similarity
# meta data of a movie 
x=["amir khan","katrina","anurag","pk","comedy"]
y=["amir khan","kareena","anurag","talaash","comedy"]

In [3]:
# convertung the list to set for better sets operation
x=set(x)
y=set(y)

In [4]:
# (x intersection y / x union y)
similarity = len(x & y) / len(x|y) 
# & - intersection
# | - union

print(similarity)

0.42857142857142855


## Edit Distance Using Levenshtien 

In [7]:
import Levenshtein

In [8]:
x = "".join(x)
print(x)

pkamir khancomedykatrinaanurag


In [9]:
y="".join(y)
print(y)

amir khancomedykareenatalaashanurag


In [12]:
Levenshtein.distance(x,y)

12

## Cosine Similarity

In [13]:
def cosine_similarity(x,y):
    x= np.array(x)
    y=np.array(y)
    # cos = a.b/ |a| * |b|
    return (x.dot(y))/np.linalg.norm(x) * np.linalg.norm(y)

In [16]:
x=["amir khan","katrina","anurag","pk","comedy"]
y=["amir khan","kareena","anurag","talaash","comedy"]

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
# Writing it vertically to perform one hot encoding
vectorizer = CountVectorizer()
array=vectorizer.fit_transform(x)

In [23]:
print(x)
# print(array)
x_array = array.toarray()
print(x_array)

['amir khan', 'katrina', 'anurag', 'pk', 'comedy']
[[1 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 1 0 0 0]]


In [32]:
y_array=vectorizer.transform(y)
print(y_array)

  (0, 0)	1
  (0, 4)	1
  (2, 1)	1
  (4, 2)	1


In [33]:
y_array = y_array.toarray()
print(y_array)

[[1 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]]


In [35]:
# Cosine similarity

# cosine_similarity(x_array,y_array)
cosine_similarity(x_array,y_array.T)

array([[1.63299316, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.81649658, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.81649658]])